export const errorEn = {
  duplicate_category: "A category with this name already exists.", duplicate_budget: "A budget already exists for this category and month.", invalid_language: "Choose System, English, or Español.",
  "check_the_highlighted_fields_and_try_again": "Check the highlighted fields and try again.",
  "something_went_wrong_try_again": "Something went wrong. Try again.",
  "local_save_failed_your_change_is_still_visible_retry_to_save_it": "Local save failed. Your change is still visible; retry to save it.",
  "local_data_is_still_loading": "Local data is still loading.",
  "local_save_failed_retry_to_save_your_change": "Local save failed. Retry to save your change.",
  "local_data_could_not_be_saved_retry_from_settings": "Local data could not be saved. Retry from Settings.",
  "local_reset_failed_your_records_remain_available": "Local reset failed. Your records remain available.",
  "local_reset_failed_try_again": "Local reset failed. Try again.",
  "mock_data_is_available_only_in_the_local_development_environment": "Mock data is available only in the local development environment.",
  "mock_data_could_not_be_saved_locally": "Mock data could not be saved locally.",
  "local_save_failed_retry_to_save_this_record": "Local save failed. Retry to save this record.",
  "this_transaction_is_no_longer_available": "This transaction is no longer available.",
  "this_budget_is_no_longer_available": "This budget is no longer available.",
  "choose_valid_calendar_months_to_copy_budgets": "Choose valid calendar months to copy budgets.",
  "source_and_target_months_must_be_different": "Source and target months must be different.",
  "no_budgets_found_in_the_source_month": "No budgets found in the source month.",
  "no_budgets_are_available_to_copy": "No budgets are available to copy.",
  "budgets_could_not_be_saved_locally_retry_to_save_your_changes": "Budgets could not be saved locally. Retry to save your changes.",
  "choose_a_supported_base_currency": "Choose a supported base currency.",
  "choose_supported_currencies": "Choose supported currencies.",
  "select_at_least_one_desired_currency": "Select at least one desired currency.",
  "the_current_base_currency_must_remain_selected": "The current base currency must remain selected.",
  "this_category_is_no_longer_available": "This category is no longer available.",
  "protected_categories_cannot_be_deleted": "Protected categories cannot be deleted.",
  "use_yyyy_mm_dd": "Use YYYY-MM-DD",
  "use_yyyy_mm": "Use YYYY-MM",
  "description_is_required": "Description is required",
  "description_is_too_long": "Description is too long",
  "enter_a_valid_positive_amount": "Enter a valid positive amount",
  "enter_a_real_calendar_date": "Enter a real calendar date",
  "enter_a_valid_positive_budget": "Enter a valid positive budget",
  "category_name_is_required": "Category name is required",
  "category_name_is_too_long": "Category name is too long",
  "category_type_must_match_transaction_type": "Category type must match transaction type",
  "select_an_existing_category": "Select an existing category",
  "archived_categories_cannot_be_selected_for_new_transactions": "Archived categories cannot be selected for new transactions",
  "select_an_expense_category": "Select an expense category",
  "archived_categories_cannot_receive_new_budgets": "Archived categories cannot receive new budgets",
  "protected_categories_cannot_be_renamed": "Protected categories cannot be renamed",
  "protected_categories_cannot_be_archived": "Protected categories cannot be archived",
  "amount_is_required": "Amount is required",
  "amount_must_not_use_exponent_notation": "Amount must not use exponent notation",
  "amount_must_be_a_decimal_number": "Amount must be a decimal number",
  "exchange_rate_must_be_greater_than_zero_message": "Exchange rate must be greater than zero",
  "amount_must_be_finite": "Amount must be finite",
  "amount_must_be_positive": "Amount must be positive",
  "amount_must_be_greater_than_zero_message": "Amount must be greater than zero",
  "money_values_must_use_the_same_currency": "Money values must use the same currency",
  "invalid_category_choices": "Invalid category choices",
  "recording_could_not_be_read_record_again_or_enter_manually": "Recording could not be read. Record again or enter manually.",
  "say_one_expense_with_a_description_amount_and_currency_record_again_or_enter_manually": "Say one expense with a description, amount, and currency. Record again or enter manually.",
  "voice_entry_supports_colombian_pesos_us_dollars_and_bol_vares_enter_other_currencies_manually": "Voice entry supports Colombian pesos, US dollars, and bolívares. Enter other currencies manually.",
  "voice_entry_is_busy_wait_a_moment_then_record_again_or_enter_manually": "Voice entry is busy. Wait a moment, then record again or enter manually.",
  "voice_entry_is_temporarily_unavailable_enter_manually": "Voice entry is temporarily unavailable. Enter manually.",
  "voice_processing_is_unavailable_check_your_connection_or_enter_manually": "Voice processing is unavailable. Check your connection or enter manually.",
  "voice_processing_took_too_long_record_again_or_enter_manually": "Voice processing took too long. Record again or enter manually.",
  "there_are_too_many_categories_for_voice_entry_enter_manually": "There are too many categories for voice entry. Enter manually.",
  "voice_entry_is_not_configured_enter_manually": "Voice entry is not configured. Enter manually."
} as const;
export const errorEs: Record<keyof typeof errorEn, string> = {
  duplicate_category: "Ya existe una categoría con este nombre.", duplicate_budget: "Ya existe un presupuesto para esta categoría y mes.", invalid_language: "Elige Sistema, English o Español.",
  "check_the_highlighted_fields_and_try_again": "Revisa los campos indicados e inténtalo de nuevo.",
  "something_went_wrong_try_again": "Ocurrió un error. Inténtalo de nuevo.",
  "local_save_failed_your_change_is_still_visible_retry_to_save_it": "No se pudo guardar localmente. El cambio sigue visible; vuelve a intentar guardarlo.",
  "local_data_is_still_loading": "Los datos locales todavía se están cargando.",
  "local_save_failed_retry_to_save_your_change": "No se pudo guardar localmente. Reintenta para guardar el cambio.",
  "local_data_could_not_be_saved_retry_from_settings": "No se pudieron guardar los datos locales. Reintenta desde Ajustes.",
  "local_reset_failed_your_records_remain_available": "No se pudo restablecer. Tus registros siguen disponibles.",
  "local_reset_failed_try_again": "No se pudo restablecer. Inténtalo de nuevo.",
  "mock_data_is_available_only_in_the_local_development_environment": "Los datos de ejemplo solo están disponibles en el entorno de desarrollo local.",
  "mock_data_could_not_be_saved_locally": "No se pudieron guardar los datos de ejemplo localmente.",
  "local_save_failed_retry_to_save_this_record": "No se pudo guardar localmente. Reintenta para guardar este registro.",
  "this_transaction_is_no_longer_available": "Esta transacción ya no está disponible.",
  "this_budget_is_no_longer_available": "Este presupuesto ya no está disponible.",
  "choose_valid_calendar_months_to_copy_budgets": "Elige meses válidos para copiar presupuestos.",
  "source_and_target_months_must_be_different": "Los meses de origen y destino deben ser diferentes.",
  "no_budgets_found_in_the_source_month": "No hay presupuestos en el mes de origen.",
  "no_budgets_are_available_to_copy": "No hay presupuestos disponibles para copiar.",
  "budgets_could_not_be_saved_locally_retry_to_save_your_changes": "No se pudieron guardar los presupuestos localmente. Reintenta para guardar los cambios.",
  "choose_a_supported_base_currency": "Elige una moneda base compatible.",
  "choose_supported_currencies": "Elige monedas compatibles.",
  "select_at_least_one_desired_currency": "Selecciona al menos una moneda.",
  "the_current_base_currency_must_remain_selected": "La moneda base actual debe permanecer seleccionada.",
  "this_category_is_no_longer_available": "Esta categoría ya no está disponible.",
  "protected_categories_cannot_be_deleted": "Las categorías protegidas no se pueden eliminar.",
  "use_yyyy_mm_dd": "Usa YYYY-MM-DD",
  "use_yyyy_mm": "Usa YYYY-MM",
  "description_is_required": "La descripción es obligatoria",
  "description_is_too_long": "La descripción es demasiado larga",
  "enter_a_valid_positive_amount": "Ingresa un monto positivo válido",
  "enter_a_real_calendar_date": "Ingresa una fecha de calendario válida",
  "enter_a_valid_positive_budget": "Ingresa un presupuesto positivo válido",
  "category_name_is_required": "El nombre de la categoría es obligatorio",
  "category_name_is_too_long": "El nombre de la categoría es demasiado largo",
  "category_type_must_match_transaction_type": "El tipo de categoría debe coincidir con el tipo de transacción",
  "select_an_existing_category": "Selecciona una categoría existente",
  "archived_categories_cannot_be_selected_for_new_transactions": "No se pueden seleccionar categorías archivadas para transacciones nuevas",
  "select_an_expense_category": "Selecciona una categoría de gastos",
  "archived_categories_cannot_receive_new_budgets": "Las categorías archivadas no pueden recibir presupuestos nuevos",
  "protected_categories_cannot_be_renamed": "Las categorías protegidas no se pueden renombrar",
  "protected_categories_cannot_be_archived": "Las categorías protegidas no se pueden archivar",
  "amount_is_required": "El monto es obligatorio",
  "amount_must_not_use_exponent_notation": "El monto no puede usar notación exponencial",
  "amount_must_be_a_decimal_number": "El monto debe ser un número decimal",
  "exchange_rate_must_be_greater_than_zero_message": "La tasa de cambio debe ser mayor que cero",
  "amount_must_be_finite": "El monto debe ser finito",
  "amount_must_be_positive": "El monto debe ser positivo",
  "amount_must_be_greater_than_zero_message": "El monto debe ser mayor que cero",
  "money_values_must_use_the_same_currency": "Los valores deben usar la misma moneda",
  "invalid_category_choices": "Selección de categorías inválida",
  "recording_could_not_be_read_record_again_or_enter_manually": "No se pudo leer la grabación. Graba de nuevo o ingresa manualmente.",
  "say_one_expense_with_a_description_amount_and_currency_record_again_or_enter_manually": "Di un gasto con descripción, monto y moneda. Graba de nuevo o ingresa manualmente.",
  "voice_entry_supports_colombian_pesos_us_dollars_and_bol_vares_enter_other_currencies_manually": "La entrada por voz admite pesos colombianos, dólares estadounidenses y bolívares. Ingresa otras monedas manualmente.",
  "voice_entry_is_busy_wait_a_moment_then_record_again_or_enter_manually": "La entrada por voz está ocupada. Espera un momento y graba de nuevo o ingresa manualmente.",
  "voice_entry_is_temporarily_unavailable_enter_manually": "La entrada por voz no está disponible temporalmente. Ingresa manualmente.",
  "voice_processing_is_unavailable_check_your_connection_or_enter_manually": "El procesamiento por voz no está disponible. Revisa tu conexión o ingresa manualmente.",
  "voice_processing_took_too_long_record_again_or_enter_manually": "El procesamiento por voz tardó demasiado. Graba de nuevo o ingresa manualmente.",
  "there_are_too_many_categories_for_voice_entry_enter_manually": "Hay demasiadas categorías para la entrada por voz. Ingresa manualmente.",
  "voice_entry_is_not_configured_enter_manually": "La entrada por voz no está configurada. Ingresa manualmente."
};
