export const budgetsEn = {
  "budgetsUpdateAMonthlyLimit": "Update a monthly limit",
  "budgetsNewMonthlyLimit": "New monthly limit",
  "budgetsEditBudget": "Edit budget",
  "budgetsCreateBudget": "Create budget",
  "budgetsCloseBudgetForm": "Close budget form",
  "budgetsEveryActiveExpenseCategoryAlreadyHasA": "Every active expense category already has a budget for this month.",
  "budgetsMonthlyLimit": "Monthly limit",
  "budgetsMonthlyBudgetAmount": "Monthly budget amount",
  "budgetsMonth": "Month",
  "budgetsBudgetMonthInYyyyMmFormat": "Budget month in YYYY-MM format",
  "budgetsSaveBudget": "Save budget",
  "budgetsReuseAMonthlyPlan": "Reuse a monthly plan",
  "budgetsCopyBudgets": "Copy budgets",
  "budgetsCloseCopyBudgetsForm": "Close copy budgets form",
  "budgetsCopyFrom": "Copy from",
  "budgetsPreviousSourceMonth": "Previous source month",
  "budgetsNextSourceMonth": "Next source month",
  "budgetsBudgetsWillBeAddedTo": "Budgets will be added to",
  "budgetsPreview": "Preview",
  "budgetsIn": "in",
  "budgetsEligibleToCopy": "eligible to copy",
  "budgetsSkippedBecauseTheCategoryAlreadyExistsOr": "skipped because the category already exists or is unavailable",
  "budgetsChooseADifferentSourceMonth": "Choose a different source month.",
  "budgetsThereAreNoBudgetsInThisSource": "There are no budgets in this source month.",
  "budgetsNothingCanBeCopiedIntoThisMonth": "Nothing can be copied into this month.",
  "budgetsCopyEligibleBudgets": "Copy eligible budgets",
  "budgetsCancelCopyingBudgets": "Cancel copying budgets",
  "budgetsBudgetUpdatedLocally": "Budget updated locally.",
  "budgetsBudgetCreatedLocally": "Budget created locally.",
  "budgetsBudgetDeletedLocally": "Budget deleted locally.",
  "budgetsMonthlyPlanning": "Monthly planning",
  "budgetsPreviousBudgetMonth": "Previous budget month",
  "budgetsNextBudgetMonth": "Next budget month",
  "budgetsCopyBudgetsFromAnotherMonth": "Copy budgets from another month",
  "budgetsCopyFromAnotherMonth": "Copy from another month",
  "budgetsCreateBudgetAlternative": "＋ Create budget",
  "budgetsDeleteThisBudgetYouCanTUndo": "Delete this budget? You can’t undo this action here.",
  "budgetsDeleteBudget": "Delete budget",
  "budgetsNoBudgetsForThisMonth": "No budgets for this month",
  "budgetsCreateACategoryLimitToCompareLocal": "Create a category limit to compare local expense activity with a monthly plan.",
  "budgetsOverBudget": "Over budget",
  "budgetsNearLimit": "Near limit",
  "budgetsOnTrack": "On track",
  "budgetsSpent": "Spent",
  "budgetsLimit": "Limit",
  "budgetsOtherCurrencySpendingIsShownSeparatelyUntil": "Other-currency spending is shown separately until an exchange rate is available.",
  "budgetsEdit": "Edit"
} as const;
export const budgetsEs: Record<keyof typeof budgetsEn, string> = {
  "budgetsUpdateAMonthlyLimit": "Actualizar un límite mensual",
  "budgetsNewMonthlyLimit": "Límite mensual nuevo",
  "budgetsEditBudget": "Editar presupuesto",
  "budgetsCreateBudget": "Crear presupuesto",
  "budgetsCloseBudgetForm": "Cerrar formulario de presupuesto",
  "budgetsEveryActiveExpenseCategoryAlreadyHasA": "Todas las categorías de gastos activas ya tienen un presupuesto este mes.",
  "budgetsMonthlyLimit": "Límite mensual",
  "budgetsMonthlyBudgetAmount": "Monto del presupuesto mensual",
  "budgetsMonth": "Mes",
  "budgetsBudgetMonthInYyyyMmFormat": "Mes del presupuesto en formato YYYY-MM",
  "budgetsSaveBudget": "Guardar presupuesto",
  "budgetsReuseAMonthlyPlan": "Reutilizar un plan mensual",
  "budgetsCopyBudgets": "Copiar presupuestos",
  "budgetsCloseCopyBudgetsForm": "Cerrar formulario de copia de presupuestos",
  "budgetsCopyFrom": "Copiar desde",
  "budgetsPreviousSourceMonth": "Mes de origen anterior",
  "budgetsNextSourceMonth": "Mes de origen siguiente",
  "budgetsBudgetsWillBeAddedTo": "Se agregarán presupuestos a",
  "budgetsPreview": "Vista previa",
  "budgetsIn": "en",
  "budgetsEligibleToCopy": "disponibles para copiar",
  "budgetsSkippedBecauseTheCategoryAlreadyExistsOr": "omitidos porque la categoría ya existe o no está disponible",
  "budgetsChooseADifferentSourceMonth": "Elige otro mes de origen.",
  "budgetsThereAreNoBudgetsInThisSource": "No hay presupuestos en este mes de origen.",
  "budgetsNothingCanBeCopiedIntoThisMonth": "No se puede copiar nada a este mes.",
  "budgetsCopyEligibleBudgets": "Copiar presupuestos disponibles",
  "budgetsCancelCopyingBudgets": "Cancelar copia de presupuestos",
  "budgetsBudgetUpdatedLocally": "Presupuesto actualizado localmente.",
  "budgetsBudgetCreatedLocally": "Presupuesto creado localmente.",
  "budgetsBudgetDeletedLocally": "Presupuesto eliminado localmente.",
  "budgetsMonthlyPlanning": "Planificación mensual",
  "budgetsPreviousBudgetMonth": "Mes de presupuesto anterior",
  "budgetsNextBudgetMonth": "Mes de presupuesto siguiente",
  "budgetsCopyBudgetsFromAnotherMonth": "Copiar presupuestos de otro mes",
  "budgetsCopyFromAnotherMonth": "Copiar desde otro mes",
  "budgetsCreateBudgetAlternative": "＋ Crear presupuesto",
  "budgetsDeleteThisBudgetYouCanTUndo": "¿Eliminar este presupuesto? No puedes deshacer esta acción aquí.",
  "budgetsDeleteBudget": "Eliminar presupuesto",
  "budgetsNoBudgetsForThisMonth": "No hay presupuestos este mes",
  "budgetsCreateACategoryLimitToCompareLocal": "Crea un límite por categoría para comparar los gastos locales con un plan mensual.",
  "budgetsOverBudget": "Presupuesto excedido",
  "budgetsNearLimit": "Cerca del límite",
  "budgetsOnTrack": "Dentro del límite",
  "budgetsSpent": "Gastado",
  "budgetsLimit": "Límite",
  "budgetsOtherCurrencySpendingIsShownSeparatelyUntil": "Los gastos en otras monedas se muestran por separado hasta que haya una tasa de cambio.",
  "budgetsEdit": "Editar"
};
