export const dashboardEn = {
  "dashboardNoTransactionsYet": "No transactions yet",
  "dashboardAddYourFirstIncomeOrExpenseTo": "Add your first income or expense to see your remaining budget and monthly picture.",
  "dashboardAddTransaction": "＋ Add transaction",
  "dashboardBaseCurrencySnapshot": "Base currency snapshot",
  "dashboardLoadingRates": "Loading rates…",
  "dashboardPartialView": "Partial view",
  "dashboardStaleRates": "Stale rates",
  "dashboardRatesAvailable": "Rates available",
  "dashboardCombinedTotalsAreUnavailableFor": "Combined totals are unavailable for",
  "dashboardOriginalCurrencyFiguresRemainBelow": ". Original-currency figures remain above.",
  "dashboardIncome": "Income",
  "dashboardExpenses": "Expenses",
  "dashboardNet": "Net",
  "dashboardNoExchangeRateIsAvailableFor": "No exchange rate is available for every currency in this view. Original-currency figures remain visible.",
  "dashboardExchangeRatesCouldNotBeRefreshedRetry": "Exchange rates could not be refreshed. Retry from Settings.",
  "dashboardRatesUseTheLatestAvailableDataEffective": "Rates use the latest available data; effective dates are shown in Settings.",
  "dashboardSameCurrencyTotalsDoNotRequireA": "Same-currency totals do not require a provider rate.",
  "dashboardIncomeAlternative": "· income",
  "dashboardRemainingBudget": "Remaining budget",
  "dashboardOriginalCurrencyBudgets": "Monthly limits minus expenses, shown in each original currency.",
  "dashboardNoBudgetSet": "No budget set",
  "dashboardCategorySpending": "Category spending",
  "dashboardThisMonth": "This month",
  "dashboardNoExpenseActivityThisMonth": "No expense activity this month.",
  "dashboardRecentActivity": "Recent activity",
  "dashboardSeeAll": "See all"
} as const;
export const dashboardEs: Record<keyof typeof dashboardEn, string> = {
  "dashboardNoTransactionsYet": "Todavía no hay transacciones",
  "dashboardAddYourFirstIncomeOrExpenseTo": "Agrega tu primer ingreso o gasto para ver el presupuesto restante y el resumen mensual.",
  "dashboardAddTransaction": "＋ Agregar transacción",
  "dashboardBaseCurrencySnapshot": "Resumen en moneda base",
  "dashboardLoadingRates": "Cargando tasas…",
  "dashboardPartialView": "Vista parcial",
  "dashboardStaleRates": "Tasas desactualizadas",
  "dashboardRatesAvailable": "Tasas disponibles",
  "dashboardCombinedTotalsAreUnavailableFor": "Los totales combinados no están disponibles para",
  "dashboardOriginalCurrencyFiguresRemainBelow": ". Los valores en monedas originales se muestran arriba.",
  "dashboardIncome": "Ingresos",
  "dashboardExpenses": "Gastos",
  "dashboardNet": "Neto",
  "dashboardNoExchangeRateIsAvailableFor": "No hay tasas de cambio para todas las monedas de esta vista. Los valores en monedas originales siguen visibles.",
  "dashboardExchangeRatesCouldNotBeRefreshedRetry": "No se pudieron actualizar las tasas de cambio. Reintenta desde Ajustes.",
  "dashboardRatesUseTheLatestAvailableDataEffective": "Las tasas usan los últimos datos disponibles; las fechas efectivas se muestran en Ajustes.",
  "dashboardSameCurrencyTotalsDoNotRequireA": "Los totales de una misma moneda no requieren una tasa del proveedor.",
  "dashboardIncomeAlternative": "· ingresos",
  "dashboardRemainingBudget": "Presupuesto restante",
  "dashboardOriginalCurrencyBudgets": "Límites mensuales menos gastos, en cada moneda original.",
  "dashboardNoBudgetSet": "Sin presupuesto",
  "dashboardCategorySpending": "Gastos por categoría",
  "dashboardThisMonth": "Este mes",
  "dashboardNoExpenseActivityThisMonth": "No hay gastos este mes.",
  "dashboardRecentActivity": "Actividad reciente",
  "dashboardSeeAll": "Ver todo"
};
