export const reportsEn = {
  "reportsFactualSummaries": "Factual summaries",
  "reportsSpendingHistory": "Spending history",
  "reportsDescriptiveOnlyNoFinancialAdvice": "Descriptive only · no financial advice",
  "reportsNoReportDataYet": "No report data yet",
  "reportsAddTransactionsToSeeMonthlyTrendsAnd": "Add transactions to see monthly trends and category breakdowns. Your original currencies will remain visible until conversion rates are available.",
  "reportsOriginalCurrenciesPreserved": "Original currencies preserved",
  "reportsReportsGroupFiguresByCurrencySoA": "Reports group figures by currency so a missing exchange rate never creates a misleading combined total.",
  "reportsBaseCurrencyTrend": "Base currency trend",
  "reportsHistoricalRates": "Historical rates ·",
  "reportsRateError": "Rate error",
  "reportsPartialData": "Partial data",
  "reportsReady": "Ready",
  "reportsSomeDatesHaveNoUsableRateYet": "Some dates have no usable rate yet, so combined historical totals remain unavailable for those currencies. Original values are still shown below.",
  "reportsExpenses": "expenses",
  "reportsIncome": "income",
  "reportsEachConversionUsesTheNearestPriorPublished": "Each conversion uses the nearest prior published rate for the transaction date; the effective date is available in Settings.",
  "reportsMonthlyExpenses": "Monthly expenses",
  "reportsLast": "Last",
  "reportsMonthsOriginalCurrencies": "months · original currencies",
  "reportsNoActivity": "No activity",
  "reportsCategoryBreakdown": "Category breakdown",
  "reportsWhatHappened": "What happened",
  "reportsAFactualActivityNote": "A factual activity note",
  "reportsThisSummaryDescribesRecordedActivityItDoes": "This summary describes recorded activity; it does not recommend actions."
} as const;
export const reportsEs: Record<keyof typeof reportsEn, string> = {
  "reportsFactualSummaries": "Resúmenes descriptivos",
  "reportsSpendingHistory": "Historial de gastos",
  "reportsDescriptiveOnlyNoFinancialAdvice": "Solo descriptivo · sin asesoría financiera",
  "reportsNoReportDataYet": "Todavía no hay datos para informes",
  "reportsAddTransactionsToSeeMonthlyTrendsAnd": "Agrega transacciones para ver tendencias mensuales y desgloses por categoría. Las monedas originales siguen visibles hasta que haya tasas de conversión disponibles.",
  "reportsOriginalCurrenciesPreserved": "Monedas originales conservadas",
  "reportsReportsGroupFiguresByCurrencySoA": "Los informes agrupan los valores por moneda para evitar totales combinados engañosos cuando falta una tasa de cambio.",
  "reportsBaseCurrencyTrend": "Tendencia en moneda base",
  "reportsHistoricalRates": "Tasas históricas ·",
  "reportsRateError": "Error de tasa",
  "reportsPartialData": "Datos parciales",
  "reportsReady": "Listo",
  "reportsSomeDatesHaveNoUsableRateYet": "Algunas fechas aún no tienen tasas utilizables, por lo que no hay totales históricos combinados para esas monedas. Los valores originales siguen abajo.",
  "reportsExpenses": "gastos",
  "reportsIncome": "ingresos",
  "reportsEachConversionUsesTheNearestPriorPublished": "Cada conversión usa la última tasa publicada antes de la fecha de la transacción; la fecha efectiva está en Ajustes.",
  "reportsMonthlyExpenses": "Gastos mensuales",
  "reportsLast": "Últimos",
  "reportsMonthsOriginalCurrencies": "meses · monedas originales",
  "reportsNoActivity": "Sin actividad",
  "reportsCategoryBreakdown": "Desglose por categoría",
  "reportsWhatHappened": "Qué ocurrió",
  "reportsAFactualActivityNote": "Una nota descriptiva de actividad",
  "reportsThisSummaryDescribesRecordedActivityItDoes": "Este resumen describe la actividad registrada; no recomienda acciones."
};
