export const settingsEn = {
  "settingsLocalDataResetNoDemoRecordsWere": "Local data reset. No demo records were added.",
  "settingsPreferencesAndPrivacy": "Preferences and privacy",
  "settingsDismissConfirmation": "Dismiss confirmation",
  "settingsAllSettings": "All settings",
  "settingsPreferences": "Preferences",
  "settingsTheseChoicesAreSavedWithYourLocal": "These choices are saved with your local dataset.",
  "settingsEnglish": "English",
  "settingsEspaOl": "Español",
  "settingsCurrencies": "Currencies",
  "settingsChooseTheCurrenciesYouWantAvailableIn": "Choose the currencies you want available in new records. Your base currency must remain selected.",
  "settingsCurrencyChoicesSavedLocally": "Currency choices saved locally.",
  "settingsBaseCurrency": "Base currency",
  "settingsUsedForFutureAggregateConversionAndNew": "Used for future aggregate conversion and new budgets. Original transaction currencies stay unchanged.",
  "settingsTheme": "Theme",
  "settingsThemePreferenceSavedLocally": "Theme preference saved locally.",
  "settingsExchangeRates": "Exchange rates",
  "settingsRateFreshnessIsShownBeforeAnyCombined": "Rate freshness is shown before any combined multi-currency total is presented.",
  "settingsLoadingRates": "Loading rates",
  "settingsRateRefreshNeedsAttention": "Rate refresh needs attention",
  "settingsReferenceRateUnavailable": "Reference rate unavailable",
  "settingsSameCurrencyTotals": "Same-currency totals",
  "settingsFetchingTheLatestAvailableReferenceRates": "Fetching the latest available reference rates.",
  "settingsTheProviderCouldNotBeReachedCached": "The provider could not be reached. Cached stale rates remain labeled when available.",
  "settingsNoProviderRateIsNeededUntilA": "No provider rate is needed until a transaction uses a different currency.",
  "settingsFrankfurterBlendedRates": "Frankfurter · blended rates",
  "settingsOriginalAmountsStayUnchangedCombinedTotalsAre": "Original amounts stay unchanged. Combined totals are omitted when no usable conversion exists.",
  "settingsRetryRateRefresh": "Retry rate refresh",
  "settingsLocalDataAndPrivacy": "Local data and privacy",
  "settingsYourTrackerIsAnonymousAndKeepsFinancial": "Your tracker is anonymous and keeps financial data on this device.",
  "settingsLocalOnlyDataset": "Local-only dataset",
  "settingsTransactions": "transactions ·",
  "settingsBudgets": "budgets ·",
  "settingsCategories": "categories",
  "settingsAnalyticsDisabled": "Analytics disabled.",
  "settingsAnalyticsEnabledWithPrivacyControls": "Analytics enabled with privacy controls.",
  "settingsOptionalAnalytics": "Optional analytics",
  "settingsEnabledFinancialValuesAndUserEnteredText": "Enabled. Financial values and user-entered text remain excluded.",
  "settingsDisabledByDefaultNoProductAnalyticsIs": "Disabled by default. No product analytics is collected.",
  "settingsResetThisLocalCopy": "Reset this local copy?",
  "settingsThisRemovesLocalTransactionsBudgetsCategoriesAnd": "This removes local transactions, budgets, categories, and preferences. There is no demo-data restore.",
  "settingsProPreview": "PRO PREVIEW",
  "settingsTakeYourRecordsWithYou": "Take your records with you",
  "settingsExpressInterestInCsvExportWithoutDownloading": "Express interest in CSV export without downloading financial data or starting a subscription.",
  "settingsIMInterested": "I’m interested",
  "settingsPersonalization": "Personalization",
  "settingsCurrencyAppearance": "Currency & appearance",
  "settingsBaseCurrencyAndTheme": "Base currency and theme",
  "settingsCategoriesAlternative": "Categories",
  "settingsCreateAndManageCategories": "Create and manage categories",
  "settingsData": "Data",
  "settingsConversionStatusAndFreshness": "Conversion status and freshness",
  "settingsLocalDataPrivacy": "Local data & privacy",
  "settingsAnalyticsAndLocalDataControls": "Analytics and local data controls",
  "settingsMore": "More",
  "settingsProFeaturePreview": "Pro feature preview",
  "settingsSettingsSections": "Settings sections",
  "settingsCategoryRenamedLocally": "Category renamed locally.",
  "settingsCategoryDeletedRelatedRecordsMovedToUncategorized": "Category deleted; related records moved to Uncategorized.",
  "settingsCreateRenameArchiveOrDeleteCategoriesProtected": "Create, rename, archive, or delete custom categories. System categories cannot be renamed, archived, or deleted.",
  "settingsNewCategoryName": "New category name",
  "settingsAddCategory": "Add category",
  "settingsProtectedSystemCategory": "Protected system category",
  "settingsArchivedHistoricalRecordsRemainVisible": "Archived · historical records remain visible",
  "settingsActive": "Active",
  "settingsSave": "Save",
  "settingsRename": "Rename",
  "settingsCategoryArchivedLocally": "Category archived locally.",
  "settingsArchive": "Archive",
  "settingsDelete": "Delete",
  "settingsDeleteAndMoveRecordsToUncategorized": "Delete and move records to Uncategorized?",
  "settingsConfirm": "Confirm"
} as const;
export const settingsEs: Record<keyof typeof settingsEn, string> = {
  "settingsLocalDataResetNoDemoRecordsWere": "Datos locales restablecidos. No se agregaron registros de ejemplo.",
  "settingsPreferencesAndPrivacy": "Preferencias y privacidad",
  "settingsDismissConfirmation": "Cerrar confirmación",
  "settingsAllSettings": "Toda la configuración",
  "settingsPreferences": "Preferencias",
  "settingsTheseChoicesAreSavedWithYourLocal": "Estas opciones se guardan con tus datos locales.",
  "settingsEnglish": "English",
  "settingsEspaOl": "Español",
  "settingsCurrencies": "Monedas",
  "settingsChooseTheCurrenciesYouWantAvailableIn": "Elige las monedas disponibles en registros nuevos. La moneda base debe permanecer seleccionada.",
  "settingsCurrencyChoicesSavedLocally": "Selección de monedas guardada localmente.",
  "settingsBaseCurrency": "Moneda base",
  "settingsUsedForFutureAggregateConversionAndNew": "Se usa para convertir totales y crear presupuestos nuevos. Las monedas originales de las transacciones se conservan.",
  "settingsTheme": "Tema",
  "settingsThemePreferenceSavedLocally": "Preferencia de tema guardada localmente.",
  "settingsExchangeRates": "Tasas de cambio",
  "settingsRateFreshnessIsShownBeforeAnyCombined": "La vigencia de las tasas se muestra antes de presentar totales de varias monedas.",
  "settingsLoadingRates": "Cargando tasas",
  "settingsRateRefreshNeedsAttention": "La actualización de tasas necesita atención",
  "settingsReferenceRateUnavailable": "Tasa de referencia no disponible",
  "settingsSameCurrencyTotals": "Totales en la misma moneda",
  "settingsFetchingTheLatestAvailableReferenceRates": "Obteniendo las últimas tasas de referencia disponibles.",
  "settingsTheProviderCouldNotBeReachedCached": "No se pudo contactar al proveedor. Las tasas almacenadas desactualizadas se identifican cuando están disponibles.",
  "settingsNoProviderRateIsNeededUntilA": "No se necesita una tasa hasta que una transacción use otra moneda.",
  "settingsFrankfurterBlendedRates": "Frankfurter · tasas combinadas",
  "settingsOriginalAmountsStayUnchangedCombinedTotalsAre": "Los montos originales se conservan. Los totales combinados se omiten cuando no hay una conversión disponible.",
  "settingsRetryRateRefresh": "Reintentar actualización de tasas",
  "settingsLocalDataAndPrivacy": "Datos locales y privacidad",
  "settingsYourTrackerIsAnonymousAndKeepsFinancial": "Tu registro es anónimo y conserva los datos financieros en este dispositivo.",
  "settingsLocalOnlyDataset": "Datos exclusivamente locales",
  "settingsTransactions": "transacciones ·",
  "settingsBudgets": "presupuestos ·",
  "settingsCategories": "categorías",
  "settingsAnalyticsDisabled": "Analítica desactivada.",
  "settingsAnalyticsEnabledWithPrivacyControls": "Analítica activada con controles de privacidad.",
  "settingsOptionalAnalytics": "Analítica opcional",
  "settingsEnabledFinancialValuesAndUserEnteredText": "Activada. Los valores financieros y el texto ingresado siguen excluidos.",
  "settingsDisabledByDefaultNoProductAnalyticsIs": "Desactivada de forma predeterminada. No se recopila analítica del producto.",
  "settingsResetThisLocalCopy": "¿Restablecer esta copia local?",
  "settingsThisRemovesLocalTransactionsBudgetsCategoriesAnd": "Esto elimina transacciones, presupuestos, categorías y preferencias locales. No hay restauración de datos de ejemplo.",
  "settingsProPreview": "VISTA PREVIA PRO",
  "settingsTakeYourRecordsWithYou": "Lleva tus registros contigo",
  "settingsExpressInterestInCsvExportWithoutDownloading": "Expresa tu interés en exportar CSV sin descargar datos financieros ni iniciar una suscripción.",
  "settingsIMInterested": "Me interesa",
  "settingsPersonalization": "Personalización",
  "settingsCurrencyAppearance": "Moneda y apariencia",
  "settingsBaseCurrencyAndTheme": "Moneda base y tema",
  "settingsCategoriesAlternative": "Categorías",
  "settingsCreateAndManageCategories": "Crear y administrar categorías",
  "settingsData": "Datos",
  "settingsConversionStatusAndFreshness": "Estado y vigencia de las conversiones",
  "settingsLocalDataPrivacy": "Datos locales y privacidad",
  "settingsAnalyticsAndLocalDataControls": "Controles de analítica y datos locales",
  "settingsMore": "Más",
  "settingsProFeaturePreview": "Vista previa de función Pro",
  "settingsSettingsSections": "Secciones de configuración",
  "settingsCategoryRenamedLocally": "Categoría renombrada localmente.",
  "settingsCategoryDeletedRelatedRecordsMovedToUncategorized": "Categoría eliminada; los registros relacionados se movieron a Sin categoría.",
  "settingsCreateRenameArchiveOrDeleteCategoriesProtected": "Crea, renombra, archiva o elimina categorías personalizadas. Las categorías del sistema no se pueden renombrar, archivar ni eliminar.",
  "settingsNewCategoryName": "Nombre de la categoría nueva",
  "settingsAddCategory": "Agregar categoría",
  "settingsProtectedSystemCategory": "Categoría protegida del sistema",
  "settingsArchivedHistoricalRecordsRemainVisible": "Archivada · los registros históricos siguen visibles",
  "settingsActive": "Activa",
  "settingsSave": "Guardar",
  "settingsRename": "Renombrar",
  "settingsCategoryArchivedLocally": "Categoría archivada localmente.",
  "settingsArchive": "Archivar",
  "settingsDelete": "Eliminar",
  "settingsDeleteAndMoveRecordsToUncategorized": "¿Eliminar y mover los registros a Sin categoría?",
  "settingsConfirm": "Confirmar"
};
