export const transactionsEn = {
  "transactionsArchivedCategory": "Archived category",
  "transactionsDeleteThisTransaction": "Delete this transaction?",
  "transactionsThisRemovesItFromTheLocalList": "This removes it from the local list. You can’t undo this action here.",
  "transactionsUpdateALocalRecord": "Update a local record",
  "transactionsNewLocalRecord": "New local record",
  "transactionsEditTransaction": "Edit transaction",
  "transactionsAddTransaction": "Add transaction",
  "transactionsCloseTransactionForm": "Close transaction form",
  "transactionsExpense": "Expense",
  "transactionsAmount": "Amount",
  "transactionsCategory": "Category",
  "transactionsCreateAnActiveCategoryInSettingsFirst": "Create an active category in Settings first.",
  "transactionsDescription": "Description",
  "transactionsWhatWasThisFor": "What was this for?",
  "transactionsDate": "Date",
  "transactionsDateInYyyyMmDdFormat": "Date in YYYY-MM-DD format",
  "transactionsCurrency": "Currency",
  "transactionsSaving": "Saving…",
  "transactionsSaveTransaction": "Save transaction",
  "transactionsClear": "Clear",
  "transactionsOpensACalendarToChooseADate": "Opens a calendar to choose a date",
  "transactionsSelectDate": "Select date",
  "transactionsTransactionUpdatedLocally": "Transaction updated locally.",
  "transactionsTransactionSavedLocally": "Transaction saved locally.",
  "transactionsTransactionDeleted": "Transaction deleted.",
  "transactionsYourLocalRecords": "Your local records",
  "transactionsSearchTransactions": "Search transactions",
  "transactionsAll": "All",
  "transactionsHideFilters": "Hide filters",
  "transactionsMoreFilters": "More filters",
  "transactionsClearFilters": "Clear filters",
  "transactionsAllCategories": "All categories",
  "transactionsAllCurrencies": "All currencies",
  "transactionsFromDate": "From date",
  "transactionsFilterFromDate": "Filter from date",
  "transactionsToDate": "To date",
  "transactionsFilterToDate": "Filter to date",
  "transactionsActivity": "Activity",
  "transactionsAddYourFirstIncomeOrExpenseTo": "Add your first income or expense to start building your local activity history.",
  "transactionsNoMatchingTransactions": "No matching transactions",
  "transactionsTryADifferentSearchOrClearThe": "Try a different search or clear the filters."
} as const;
export const transactionsEs: Record<keyof typeof transactionsEn, string> = {
  "transactionsArchivedCategory": "Categoría archivada",
  "transactionsDeleteThisTransaction": "¿Eliminar esta transacción?",
  "transactionsThisRemovesItFromTheLocalList": "Esto la elimina de la lista local. No puedes deshacer esta acción aquí.",
  "transactionsUpdateALocalRecord": "Actualizar un registro local",
  "transactionsNewLocalRecord": "Registro local nuevo",
  "transactionsEditTransaction": "Editar transacción",
  "transactionsAddTransaction": "Agregar transacción",
  "transactionsCloseTransactionForm": "Cerrar formulario de transacción",
  "transactionsExpense": "Gasto",
  "transactionsAmount": "Monto",
  "transactionsCategory": "Categoría",
  "transactionsCreateAnActiveCategoryInSettingsFirst": "Primero crea una categoría activa en Ajustes.",
  "transactionsDescription": "Descripción",
  "transactionsWhatWasThisFor": "¿Para qué fue?",
  "transactionsDate": "Fecha",
  "transactionsDateInYyyyMmDdFormat": "Fecha en formato YYYY-MM-DD",
  "transactionsCurrency": "Moneda",
  "transactionsSaving": "Guardando…",
  "transactionsSaveTransaction": "Guardar transacción",
  "transactionsClear": "Limpiar",
  "transactionsOpensACalendarToChooseADate": "Abre un calendario para elegir una fecha",
  "transactionsSelectDate": "Seleccionar fecha",
  "transactionsTransactionUpdatedLocally": "Transacción actualizada localmente.",
  "transactionsTransactionSavedLocally": "Transacción guardada localmente.",
  "transactionsTransactionDeleted": "Transacción eliminada.",
  "transactionsYourLocalRecords": "Tus registros locales",
  "transactionsSearchTransactions": "Buscar transacciones",
  "transactionsAll": "Todo",
  "transactionsHideFilters": "Ocultar filtros",
  "transactionsMoreFilters": "Más filtros",
  "transactionsClearFilters": "Limpiar filtros",
  "transactionsAllCategories": "Todas las categorías",
  "transactionsAllCurrencies": "Todas las monedas",
  "transactionsFromDate": "Desde",
  "transactionsFilterFromDate": "Filtrar desde fecha",
  "transactionsToDate": "Hasta",
  "transactionsFilterToDate": "Filtrar hasta fecha",
  "transactionsActivity": "Actividad",
  "transactionsAddYourFirstIncomeOrExpenseTo": "Agrega tu primer ingreso o gasto para empezar tu historial local.",
  "transactionsNoMatchingTransactions": "No hay transacciones que coincidan",
  "transactionsTryADifferentSearchOrClearThe": "Prueba otra búsqueda o limpia los filtros."
};
