export const voiceEn = {
  "voiceRecordingReleaseToSubmit15SecondLimit": "Recording · release to submit · 15 second limit",
  "voiceWaitingForMicrophonePermission": "Waiting for microphone permission",
  "voiceStartingMicrophone": "Starting microphone…",
  "voiceSavingLocally": "Saving locally…",
  "voiceProcessingExpense": "Processing expense…",
  "voiceSavingExpenseLocally": "Saving expense locally",
  "voiceProcessingVoiceExpense": "Processing voice expense",
  "voiceRetrySave": "Retry save",
  "voiceStopAndSubmit": "Stop and submit",
  "voiceClose": "Close",
  "voiceDismiss": "Dismiss",
  "voiceEnterManually": "Enter manually",
  "voiceRecordAgain": "Record again",
  "voiceVoiceProviderMissing": "Voice provider missing",
  "voiceThisTransactionIsNoLongerAvailable": "This transaction is no longer available.",
  "voiceUncategorized": "Uncategorized",
  "voiceLocalDataIsStillLoading": "Local data is still loading.",
  "voiceLocalSaveFailedRetrySaveToKeep": "Local save failed. Retry save to keep this record without recording again.",
  "voiceMicrophoneRecordingIsUnavailableEnterManually": "Microphone recording is unavailable. Enter manually.",
  "voiceMicrophoneReadyHoldAgainOrChooseStart": "Microphone ready. Hold again or choose Start recording.",
  "voiceMicrophonePermissionWasDeniedAllowItIn": "Microphone permission was denied. Allow it in device settings or enter manually.",
  "voiceMicrophoneRecordingIsUnavailableCheckPermissionAnd": "Microphone recording is unavailable. Check permission and browser recording support, or enter manually.",
  "voiceHoldToRecordAnExpense": "Hold to record an expense",
  "voiceReleaseToSubmitAlternativelyUseStartRecording": "Release to submit. Alternatively use Start recording and Stop and submit.",
  "voiceRecording": "Recording…",
  "voiceHoldToRecordExpense": "Hold to record expense",
  "voiceStartRecording": "Start recording",
  "voiceVoiceAudioIsSentToVercelSpacexai": "Voice audio is sent to Vercel/SpaceXAI; the transcript and active category names go to Cloudflare. Say one expense: “Lunch forty thousand pesos”. The saved record stays on this device."
} as const;
export const voiceEs: Record<keyof typeof voiceEn, string> = {
  "voiceRecordingReleaseToSubmit15SecondLimit": "Grabando · suelta para enviar · límite de 15 segundos",
  "voiceWaitingForMicrophonePermission": "Esperando permiso del micrófono",
  "voiceStartingMicrophone": "Iniciando micrófono…",
  "voiceSavingLocally": "Guardando localmente…",
  "voiceProcessingExpense": "Procesando gasto…",
  "voiceSavingExpenseLocally": "Guardando gasto localmente",
  "voiceProcessingVoiceExpense": "Procesando gasto por voz",
  "voiceRetrySave": "Reintentar guardado",
  "voiceStopAndSubmit": "Detener y enviar",
  "voiceClose": "Cerrar",
  "voiceDismiss": "Descartar",
  "voiceEnterManually": "Ingresar manualmente",
  "voiceRecordAgain": "Grabar de nuevo",
  "voiceVoiceProviderMissing": "Falta el proveedor de voz",
  "voiceThisTransactionIsNoLongerAvailable": "Esta transacción ya no está disponible.",
  "voiceUncategorized": "Sin categoría",
  "voiceLocalDataIsStillLoading": "Los datos locales todavía se están cargando.",
  "voiceLocalSaveFailedRetrySaveToKeep": "No se pudo guardar localmente. Reintenta el guardado para conservar este registro sin volver a grabar.",
  "voiceMicrophoneRecordingIsUnavailableEnterManually": "La grabación con micrófono no está disponible. Ingresa manualmente.",
  "voiceMicrophoneReadyHoldAgainOrChooseStart": "Micrófono listo. Mantén presionado de nuevo o elige Iniciar grabación.",
  "voiceMicrophonePermissionWasDeniedAllowItIn": "Se denegó el permiso del micrófono. Permítelo en la configuración del dispositivo o ingresa manualmente.",
  "voiceMicrophoneRecordingIsUnavailableCheckPermissionAnd": "La grabación con micrófono no está disponible. Revisa el permiso y la compatibilidad del navegador o ingresa manualmente.",
  "voiceHoldToRecordAnExpense": "Mantén presionado para grabar un gasto",
  "voiceReleaseToSubmitAlternativelyUseStartRecording": "Suelta para enviar. También puedes usar Iniciar grabación y Detener y enviar.",
  "voiceRecording": "Grabando…",
  "voiceHoldToRecordExpense": "Mantén presionado para grabar un gasto",
  "voiceStartRecording": "Iniciar grabación",
  "voiceVoiceAudioIsSentToVercelSpacexai": "El audio se envía a Vercel/SpaceXAI; la transcripción y los nombres de categorías activas van a Cloudflare. Di un gasto: «Almuerzo cuarenta mil pesos». El registro guardado permanece en este dispositivo."
};
